# yaml键值对嵌套：即python中字典嵌套字典
# 分段yaml文件中多个文档
---
login_page:
    right_login:
      open_url: https://www.polyv.net/
      email: xxx
      password: xxx
    wrong_login:
      open_url: https://www.polyv.net/
      email: xxx
      password: xxx
---
other_page:
    test_page:
      name: test

    test_page2:
      name: test2

